### PR TITLE
added size function for RectangleGrid

### PR DESCRIPTION
**Pull request by mattuntergassmair**

### CODE REVIEW

**Comment by mykelk** [comment]
Looks good to me.

**Comment by mattuntergassmair** [comment]
Can someone with write access merge please?
@rejuvyesh @MaximeBouton @zsunberg @mykelk

**Comment by MaximeBouton** [comment]
We should probably tag a new version with this feature, unsure if it is a minor or patch release?

**Comment by mykelk** [comment]
You can make it a minor one since it adds to the API.

**Pull request merged**
