### PR TITLE
Remove redundant interpolate method for matrixes

### LINKED ISSUE #48: Redundant and allocating method for matrixes
Here: https://github.com/sisl/GridInterpolations.jl/blob/a955ae2ff6ab74491daa7ce72c2bb401e289d137/src/GridInterpolations.jl#L142

Because: 

```julia
julia> Matrix
Matrix (alias for Array{T, 2} where T)
```

and there is already a method for `Array`, it seems like this method isn't needed, so could be deleted, and it reallocates the entire array, so should be avoided. But maybe I misunderstand something?

### PR DESCRIPTION
**Pull request by ctessum**
fixes #48

### CODE REVIEW

**Comment by zsunberg** [comment]
@ctessum This is redundant with #47 and can be closed, right?

**Comment by ctessum** [comment]
I don't think it's redundant.

The function in question is still there: https://github.com/sisl/GridInterpolations.jl/blob/master/src/GridInterpolations.jl#L142

The original function makes a copy of the matrix as Float64s, and  #47 changes that to make a copy of the matrix in the same number type as the original matrix, but what I think is called for is just deleting that function entirely, because I don't think there's any reason to make a copy of that array. (But I could be wrong.)

**Comment by zsunberg** [comment]
oops, sorry! I thought you removed the function in #47, but I didn't look closely.

**Comment by zsunberg** [comment]
@himanshugupta1009 you mentioned this to me to day. Just wanted to make sure you saw this. Still would be nice to upgrade `DenseArray` to `AbstractArray` in another PR like you mentioned.

**Comment by himanshugupta1009** [comment]
@zsunberg  yes, I will make the change and raise a PR today.

**Pull request merged**
