### PR TITLE
Update to julia 0.6

### PR DESCRIPTION
**Pull request by MaximeBouton**
- Syntax changes for julia 0.6 compatibility
- Modifications of the tests to use Interpolations.jl

### CODE REVIEW

**Comment by MaximeBouton** [comment]
julia 0.4 and 0.5 should be removed from the Travis config file

**Comment by mykelk** [comment]
This looks good to merge. But, do the types need to be `mutable struct` rather than just `struct`?

**Comment by MaximeBouton** [comment]
According to julia 0.6 releases notes, type maps to mutable struct and immutable types map to struct. I haven't check if RectangleGrid and Simplex could actually be made immutable.

**Comment by mykelk** [comment]
We can keep them mutable. Let's go ahead and merge. You can push the button if you're good with it.

**Comment by MaximeBouton** [comment]
I do not have the access to merge it actually.

**Pull request merged**
